### ISSUE TITLE
uninitialized constant Chef::Knife::AzurermBase (NameError)

### ISSUE THREAD

**Issue by holmesb** [chef/knife-azure#421]
Trying to run knife azure for the first time.  It errors:

```
:~/chef-repo$ cat /opt/chefdk/version-manifest.txt |grep chef-dk
chef-dk                              local_source        path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder                             
chef-dk-appbundle                    local_source        path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files               
chef-dk-cleanup                      1.2.22              
chef-dk-complete                     1.2.22              
chef-dk-gem-binding_of_caller        0.7.2               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-byebug                   9.0.6               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-cookstyle                1.2.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-debug_inspector          0.0.2               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-dep-selector-libgecode   1.3.1               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-dep_selector             1.0.4               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-ffi                      1.9.17              path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-ffi-rzmq                 2.0.4               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-ffi-yajl                 2.3.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-hitimes                  1.2.4               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-json                     1.8.6               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-libyajl2                 1.2.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-mini_portile2            2.1.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-nio4r                    2.0.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-nokogiri                 1.6.8.1             path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-pkg-config               <skip>              path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-ruby-prof                0.16.2              path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-ruby-shadow              2.5.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem   
chef-dk-gem-yajl-ruby                1.3.0               path:/home/jenkins/workspace/chefdk-build/architecture/x86_64/platform/ubuntu-12.04/project/chefdk/role/builder/omnibus/files/chef-dk-gem  
:~/chef-repo$ chef gem install knife-azure
Successfully installed knife-azure-1.7.0
1 gem installed
:~/chef-repo$ knife azure
/home/brendan/.chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_delete.rb:31:in `<class:AzurermServerDelete>': uninitialized constant Chef::Knife::AzurermBase (NameError)
	from /home/brendan/.chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_delete.rb:29:in `<class:Knife>'
	from /home/brendan/.chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_delete.rb:28:in `<class:Chef>'
	from /home/brendan/.chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_delete.rb:27:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:100:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:100:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:110:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:57:in `load'
	from /usr/bin/knife:57:in `<main>'```

**Comment by holmesb** [comment]
Seems I missed these instructions (linked from readme.md) to connect in ARM mode:

> Put the following in your knife.rb
> 
> knife[:azure_tenant_id] # found via: tenantId=$(azure account show -s <subscriptionId> --json | jq -r '.[0].tenantId')
> knife[:azure_subscription_id] # found via: <subscriptionId>
> knife[:azure_client_id] # appId=$(azure ad app show --search <principleappcreated> --json | jq -r '.[0].appId')
> knife[:azure_client_secret] # password you set at initally

But still doesn't work.  Should the above be pasted in literally?  Or should you replace eg knife[:azure_tenant_id] with knife[:<AZURE_TENANT_ID>] or should this be:
knife[:azure_tenant_id] = "<AZURE_TENANT_ID>"
?
Isn't clear.

**Comment by predatorian3** [comment]
@holmesb I think you'd have to install the Azure CLI program in order to get that information, because I don't know where to look in the UI as well to get the information. A lot could be cleaned up and clarified with actual examples and maybe one of those fancy GIF's that shows where to find the information. 

I'm running ChefDK and using the knife-azure 1.7.0 RubyGem. 

```$ chef -v
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-04-08T11:25:38.936094 22209] 2017-04-08T11:25:38.936460 22209] 2017-04-08T11:25:38.936644 22209] 2017-04-08T11:25:38.936793 22209] 2017-04-08T11:25:38.989087 22209] 2017-04-08T11:25:38.989351 22209] 5.6.0
kitchen version: 1.15.0
```
Same error as you. It might be something simple that didn't make it through testing.

**Comment by Ranjith9** [comment]
go to the file azurerm_server_delete.rb 
replace the required file "require File.expand_path('../azure_base', __FILE__)" with the following

"require File.expand_path('../azurerm_base', __FILE__)"

**Comment by NimishaS** [comment]
@holmesb , Please refer the configuration section of ARM: https://github.com/chef/knife-azure#configuration

If you're still experiencing this issue please provide additional information and we'll be happy to help again.
