### ISSUE TITLE
Unable to launch VM using azurerm

### ISSUE THREAD

**Issue by rahulkumardbit** [chef/knife-azure#442]
I have moved from ASM to ARM and after required configuration, when I am trying to launch a VM I am getting this issue.

Command:
``knife azurerm server create --azure-resource-group-name 'testrg1' --azure-vm-name 'devopsvm' --azure-service-location 'eastus' --azure-image-reference-publisher 'OpenLogic' --azure-image-reference-offer 'CentOS' azure-image-reference-sku '7.1' --azure-image-reference-version 'latest' -azure-vm-size 'Small' --ssh-user 'azureuser' --ssh-password 'password@123'
``

Error:
``
DEBUG: {
  "message": "MsRestAzure::AzureOperationError",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}",
    "method": "head",
    "path_params": {
      "resourceGroupName": "devoprg1",
      "subscriptionId": "xxxxxxxx-xxxxxx-xxxx-xxxx-xxxxxxxxx"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "api-version": "2016-02-01"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "x-ms-client-request-id": "f7a71b8d-6443-4b3e-a025-ae4d5c679feb",
      "accept-language": "en-US"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-length": "348",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-request-id": "d7a41e3b-bcb6-4727-b792-7be730696201",
      "x-ms-correlation-request-id": "d7a41e3b-bcb6-4727-b792-7be730696201",
      "x-ms-routing-request-id": "WESTINDIA:20170718T065203Z:d7a41e3b-bcb6-4727-b792-7be730696201",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Tue, 18 Jul 2017 06:52:02 GMT",
      "connection": "close"
    },
    "status": 403
  }
}
ERROR: Something went wrong. Please use -VV option for more details.
DEBUG: C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/azure_mgmt_resources-0.3.1/lib/azure_mgmt_resources/resource_groups.rb:195:in `block in check_existence_async'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/promise.rb:501:in `block in on_fulfill'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_execu
tor.rb:24:in `block in execute'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lock
able_object.rb:38:in `block in synchronize'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/promise.rb:531:in `block in realize'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.3.0/gems/concurrent-ruby-.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
``

I am unable to understand this part and how to solve it.

**Comment by rahulkumardbit** [comment]
It was an authentication Issue.
