### ISSUE TITLE
Improper error handling, always displays "Something went wrong".

### ISSUE THREAD

**Issue by Nimesh-Msys** [chef/knife-azure#498]
# Version:

Knife-Azure- 1.9.0
Chef-Client-15.0.293

# Environment:

Windows-10

# Scenario:

For almost all the error messages, knife-azure exits as follows:

```bash
ERROR: <Error Message>
ERROR: Something went wrong. Please use -VV option for more details.
```
# Steps to Reproduce:

Assuming that a VM has already been bootstrapped over MyVM. Simply try to bootstrap that VM again,

```bash
knife bootstrap azurerm MyVM --azure-resource-group-name ValidRSG --azure-service-location "WestIndia" -N Node-1
```

# Expected Result:

```bash
ERROR: Virtual machine MyVM already has Chef extension installed on it.
```
# Actual Result:

```bash
ERROR: Virtual machine MyVM already has Chef extension installed on it.
ERROR: Something went wrong. Please use -VV option for more details.
```

# Analysis:

On further analysis, I found that it is due to improper handling in [common_arm_rescue_block](https://github.com/chef/knife-azure/blob/master/lib/azure/resource_management/ARM_interface.rb#L501-L508).
When any [string error message is raised](https://github.com/chef/knife-azure/blob/master/lib/chef/knife/bootstrap_azurerm.rb#L73), it made an attempt to parse that string, assuming that it is JSON, as it is, as a result, this handling always raises `JSON::ParserError Exception`

```ruby

   500:         else
   501:           begin
=> 502:             JSON.parse(error.message)
   503:             Chef::Log.debug("#{error.message}")
   504:           rescue JSON::ParserError => e
   505:             ui.error("#{error.message}")

# DRY-Run:

error
=> <RuntimeError: Virtual machine MyVM already has Chef extension installed on it.>

error.message
=> "Virtual machine MyVM already has Chef extension installed on it."

JSON.parse(error.message)
=> *** JSON::ParserError Exception: 785: unexpected token at 'Virtual machine MyVM already has Chef extension installed on it.'
```

On the other hand, Expected `MsRestAzure::AzureOperationError`, exits nicely:

```bash
ERROR: Resource group 'Invalid-RSG' could not be found.
```

**Comment by Nimesh-Msys** [comment]
Its backtrace, when using `-VV` (or `-V -V`) option:

```bash
ERROR: Virtual machine MyVM already has Chef extension installed on it.
ERROR: Something went wrong. Please use -VV option for more details.
DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-azure-1.9.0/lib/chef/knife/bootstrap_azurerm.rb:73:in `set_ext_params'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-azure-1.9.0/lib/chef/knife/bootstrap_azurerm.rb:49:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:221:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/bin/knife:24:in `<top (required)>'
C:/opscode/chef/bin/knife:167:in `load'
C:/opscode/chef/bin/knife:167:in `<main>'
```
